name: msgr_messages
description: "Domain models for msgr chat messages used across clients."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  meta: ^1.15.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
