name: libmsgr
description: A starting point for Dart libraries or applications.
version: 0.1.2
repository: https://github.com/msgr-no/flutter_client

environment:
  sdk: ^3.5.1

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

# Add regular dependencies here.
dependencies:
  get_it: ^7.7.0
  uuid: ^4.4.2
  shared_preferences: ^2.3.2

  # Crypto
  cryptography: ^2.7.0
  crypto: ^3.0.5
  elliptic: ^0.3.10
  pointycastle: ^3.7.3
  # Misc
  convert: ^3.1.1
  basic_utils: ^5.7.0
  dartz: ^0.10.1
  # MAYBE
  #bip32_ed25519: ^0.6.0
  #flutter_webrtc: ^0.11.6+hotfix.1
  #libsignal_protocol_dart: ^0.7.1

  #flutter_flipperkit: ^0.0.29
  #flipperkit_redux_middleware: ^0.0.4


  # This is for the storage layer (db)
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption

  # Database
  sqflite: ^2.3.3+2
  sqflite_common: ^2.5.4+4
  sqflite_sqlcipher: ^3.4.0
  #sqflite_migration: ^0.3.0
  meta: ^1.15.0
  # HTTP Client
  http: ^1.2.2
  # For communication with phoenix v1
  phoenix_socket:
    path: ../phoenix_socket
  jwt_decoder: ^2.0.1
  redux: ^5.0.0


  # Life is hard without logging
  logging: ^1.2.0
  freezed_annotation: ^2.4.4
  built_value: ^8.9.2
  path: ^1.8.0

dev_dependencies:
  sqflite_common_ffi: ^2.3.3+1
  # CLI Example
  cli_menu: ^0.4.0+1
  cli_util: ^0.4.1
  args: ^2.5.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  # Immutable
  freezed: ^2.5.7
  # Code stuff
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  built_value_generator: ^8.9.2

  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
